disabled_rules: # rule identifiers to exclude from running
  - trailing_whitespace
  - trailing_newline
  
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - VendingMachine/BeverageTests/CoffeeTests.swift
  - VendingMachine/BeverageTests/MilkTests.swift
  - VendingMachine/BeverageTests/SodaTests.swift
  - VendingMachine/BeverageTests/BeverageTests.swift
  - Pods
