# Uncomment the next line to define a global platform for your project
# platform :ios, '10.13'

target 'VendingMachine' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'SwiftLint'
  # Pods for VendingMachine

end
